### ISSUE TITLE
crashing candle manager addon due to invalid ELF header

### ISSUE THREAD

**Issue by RMHogervorst** [createcandle/Candle-manager-addon#22]
Hi there, the candle manager is suddenly crashing, any idea how to fix this?

logs:

```
2020-09-02 15:53:28.530 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/Candle-manager-addon-1.1.0-linux-arm-v3.7.tgz as /tmp/Jo4I5M/Candle-manager-addon.tar.gz
2020-09-02 15:53:38.215 INFO   : Expanding add-on /tmp/Jo4I5M/Candle-manager-addon.tar.gz
2020-09-02 15:53:44.448 INFO   : Loading add-on: Candle-manager-addon
2020-09-02 15:53:44.843 ERROR  : Candle-manager-addon: Traceback (most recent call last):
2020-09-02 15:53:44.845 ERROR  : Candle-manager-addon:   File "/home/pi/.mozilla-iot/addons/Candle-manager-addon/main.py", line 11, in <module>
2020-09-02 15:53:44.846 ERROR  : Candle-manager-addon:     from pkg.candle_adapter import CandleAdapter  # noqa
2020-09-02 15:53:44.848 ERROR  : Candle-manager-addon:   File "/home/pi/.mozilla-iot/addons/Candle-manager-addon/pkg/candle_adapter.py", line 9, in <module>
2020-09-02 15:53:44.850 ERROR  : Candle-manager-addon:     import asyncio
2020-09-02 15:53:44.851 ERROR  : Candle-manager-addon:   File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
2020-09-02 15:53:44.853 ERROR  : Candle-manager-addon:     from .base_events import *
2020-09-02 15:53:44.868 ERROR  : Candle-manager-addon:   File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
2020-09-02 15:53:44.870 ERROR  : Candle-manager-addon:     from . import events
2020-09-02 15:53:44.872 ERROR  : Candle-manager-addon:   File "/usr/lib/python3.7/asyncio/events.py", line 14, in <module>
2020-09-02 15:53:44.873 ERROR  : Candle-manager-addon:     import contextvars
2020-09-02 15:53:44.875 ERROR  : Candle-manager-addon:   File "/usr/lib/python3.7/contextvars.py", line 1, in <module>
2020-09-02 15:53:44.876 ERROR  : Candle-manager-addon:     from _contextvars import Context, ContextVar, Token, copy_context
2020-09-02 15:53:44.878 ERROR  : Candle-manager-addon: ImportError: /usr/lib/python3.7/lib-dynload/_contextvars.cpython-37m-arm-linux-gnueabihf.so: invalid ELF header
2
```

details:
I suddenly crashed, and so here is what I did. 
I removed all other addons, reinstalled the candlemanager addon. removed all 'things'
No joy.
I will now retry installing the mozilla framework on my raspberry pi

**Comment by RMHogervorst** [comment]
reinstalling gateway on raspberry pi has 'fixed' my problem

**Comment by createcandle** [comment]
Indeed, Candle is only guaranteerd to work on the Raspberry Pi image.

**Comment by RMHogervorst** [comment]
Wait, I think you misunderstood. It was installed on rpi all the time but it failed after a while. The re-imaging fixed the problem for now. But that is only a surface solution.

**Comment by createcandle** [comment]
I've removed the asyncio requirement. Hopefully that will solve this.
