### ISSUE TITLE
checksum failed for candle_cleaner.ino

### ISSUE THREAD

**Issue by RMHogervorst** [createcandle/Candle-manager-addon#23]
The candle manager addon crashes on my raspberry pi.

- reimaged the sd card yesterday, and reinstalled candle manager and it worked untill today. 

```
2020-09-03 09:12:08.929 ERROR  : Failed to restart add-on Candle-manager-addon
2020-09-03 09:12:08.941 ERROR  : Error: Checksum failed for file /home/pi/.mozilla-iot/addons/Candle-manager-addon/code/Candle_cleaner/Candle_cleaner.ino in add-on Candle-manager-addon
    at find.fileSync.forEach (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:215:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:197:1)
    at Object.loadManifest (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:303:1)
    at AddonManager.loadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:614:1)
    at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:114:1)

```

**Comment by createcandle** [comment]
I've overhauled the code to help avoid this issue.
