### ISSUE TITLE
Required dependency flask not installed during setup

### ISSUE THREAD

**Issue by rphil40** [createcandle/Candle-manager-addon#27]
Following the steps on https://www.candlesmarthome.com/controller, could not open Candle Manager page from menu. Logs show
```
2020-12-25 23:32:57.198 ERROR  : Candle-manager-addon: Traceback (most recent call last):
2020-12-25 23:32:57.200 ERROR  : Candle-manager-addon:   File "/home/pi/.webthings/addons/Candle-manager-addon/main.py", line 11, in <module>
2020-12-25 23:32:57.202 ERROR  : Candle-manager-addon:     from pkg.candle_adapter import CandleAdapter  # noqa
2020-12-25 23:32:57.204 ERROR  : Candle-manager-addon:   File "/home/pi/.webthings/addons/Candle-manager-addon/pkg/candle_adapter.py", line 27, in <module>
2020-12-25 23:32:57.206 ERROR  : Candle-manager-addon:     from flask import Flask,Response,request,render_template,jsonify,url_for
2020-12-25 23:32:57.208 ERROR  : Candle-manager-addon: ModuleNotFoundError: No module named 'flask'

```

SSHing to the Pi and running '''pip3 install flask''' resolves issue, but should probably be handled on installation already.

**Comment by createcandle** [comment]
Are you using a Raspberry Pi with the disk image? Could you tell me more about your setup? Have you tried re-installing and rebooting?

**Comment by rphil40** [comment]
Yeah, RPi 4 with the disk image from WebThings, installed the addon through the Add On page in the gateway. Not sure what else I can tell you about the setup.

Didn't reinstall as installing the library myself was easier.

**Comment by createcandle** [comment]
I've found the issue. It should be fixed asap.
